### ISSUE TITLE
Commit comments are not added

### ISSUE THREAD

**Issue by openjck** [mdn/discord#46] opened 2015-06-04 16:57 UTC
Quoting @darkwing:

> Here's what I've done that is *not* yet working:
>
> 1.  Go to my GitHub settings, created a Personal Access Token with the permissions:  admin:org_hook, admin:repo_hook, gist, repo, user
>
> 2.  Added token to my env:  export OAUTH_TOKEN=XXXXXX
>
> 3.  Added a commit to my test repo's master branch, pushed to GitHub
>
> 4.  Checked out the commit display on GitHub...no comments :(
>
> The Personal Access Tokens page also mentions the token has never been used.

**Comment by openjck** [comment] 2015-06-04 17:00
@mrmakeit: David's setup looks good to me. Can you think of something he's missing?

**Comment by mrmakeit** [comment] 2015-06-04 17:02
I'm checking it out now.

**Comment by darkwing** [comment] 2015-06-04 17:03
I haven't re-pushed to heroku with the OAUTH_TOKEN in the env -- could that be the problem?

**Comment by mrmakeit** [comment] 2015-06-04 17:04
Heroku should auto-reload the app, but doing manually couldn't hurt.
Also, can you add a link to your test repo?

**Comment by darkwing** [comment] 2015-06-04 17:05
Will try that in a moment.  Test is here:

https://github.com/darkwing/compat-tables

**Comment by mrmakeit** [comment] 2015-06-04 17:50
After running your `incompatable.css` through the `doiuse` cli, it appears that it is fully supported by the last 2 versions of every browser, as well as all versions of ie greater than 7.  This suggests that the `doiuse` package is broken, which can be confirmed by adding >1% to the .doiuse file, and getting results on Opera.

Looks like this will need to go upstream.

**Comment by mrmakeit** [comment] 2015-06-04 17:51
also, @darkwing, I highly recommend adding the .doiuse config to be certain we're testing the same group of browsers.  The `latest 2 versions` default is not reliable for testing.

**Comment by mrmakeit** [comment] 2015-06-04 18:08
I've reviewed the updated `caniuse` database, which now marks box-sizing as supported in our test case.  The `incompatable.css` file is no longer reliable for testing.

**Comment by groovecoder** [comment] 2015-06-04 18:24
Wow, good find @mrmakeit

**Comment by mrmakeit** [comment] 2015-06-04 18:24
closing as `working as intended`

**Comment by mrmakeit** [comment] 2015-06-04 18:24
@groovecoder thanks.

**Comment by openjck** [comment] 2015-06-04 21:54
Looks like something else is causing this issue. I'm [not seeing comments either](https://github.com/openjck/YouShouldUse-test/commit/3928f8241c4c6e4bf207be1950630058f50ffe74) even though my `.doiuse` configuration file tells the service to check against versions of IE >= 6.

**Comment by mrmakeit** [comment] 2015-06-04 22:01
Apparently, the caniuse database only lists Opera as a recent browser without box-sizing support.  I'm thinking they had a bad update.

**Comment by openjck** [comment] 2015-06-05 15:22
I wonder if something else might be causing this. I'm seeing compatibility warnings when I use the npm command-line tool directly, but I'm not seeing warnings in the GitHub commit.

Command-line:

```
$ npm list -g | grep doiuse
├─┬ doiuse@1.0.1
$ cat .doiuse
last 2 versions, ie >= 6
$ doiuse --browsers "last 2 versions, ie >= 6" transition.css
transition.css:2:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:3:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:4:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:5:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:6:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:7:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:8:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:9:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:10:1: CSS3 Transitions not supported by: IE (6,7,8,9)
transition.css:11:1: CSS3 Transitions not supported by: IE (6,7,8,9)
```

Commit:

https://github.com/openjck/YouShouldUse-test/commit/7c5c0c4b24c06afde0a194ce04958953ba07707b

**Comment by mrmakeit** [comment] 2015-06-05 17:09
https://github.com/mrmakeit/github-todo-test/commit/2fb10839d96361ad7859c542ccfc05405924acd5
Via the current master through the deployed heroku app.

**Comment by mrmakeit** [comment] 2015-06-05 17:11
please try switching your webhook to the official app, and see if that works for you as well.

**Comment by openjck** [comment] 2015-06-05 18:39
Interesting, it does work with `youshoulduse.herokuapp.com`.

**Comment by openjck** [comment] 2015-06-05 18:40
Interesting. The `youshoulduse.herokuapp.com` app works, and for some reason, my version is now working as well.

Did you want to give it another shot David?

**Comment by darkwing** [comment] 2015-06-12 19:21
Unfortunately I need to reopen this;  an update:

1.  I've added a `.doiuse` file to my test repo:  https://github.com/darkwing/compat-tables/blob/master/.doiuse

2.  I followed the steps in the original bug report again, (adding my OAUTH_TOKEN), then did a push to both my personal YouShouldUse and compat-table repos, and still I do not get a comment on my commits.  GitHub still says my auth token has not been used.

3.  I did add a separate web hook for the main youshoulduse.heroku.... address and it *did* leave a comment.

Anything I could be missing?

**Comment by darkwing** [comment] 2015-06-12 20:39
I've also just done the following:

```
heroku config:set GITHUB_USERNAME=darkwing
heroku config:set OAUTH_TOKEN=######
```

No comment upon next commit.

**Comment by groovecoder** [comment] 2015-06-12 20:41
FWIW, heroku logs showing:
```
davidwalsh: I see 2015-06-12T18:56:31.453485+00:00 app[web.1]: Repo: darkwing/compat-tables
2015-06-12T18:56:31.447554+00:00 app[web.1]: Fri, 12 Jun 2015 18:56:31 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at module.js:13:9
2015-06-12T18:56:31.456910+00:00 app[web.1]: TypeError: Cannot read property 'id' of undefined
2015-06-12T18:56:31.456913+00:00 app[web.1]:     at github (/app/module.js:20:95)
2015-06-12T18:56:31.456915+00:00 app[web.1]:     at hook (/app/module.js:14:5)
2015-06-12T18:56:31.456922+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
2015-06-12T18:56:31.456923+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:110:13)
2015-06-12T18:56:31.456925+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
2015-06-12T18:56:31.456926+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
2015-06-12T18:56:31.456927+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:267:22
2015-06-12T18:56:31.456928+00:00 app[web.1]:     at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
2015-06-12T18:56:31.456929+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:261:10)
2015-06-12T18:56:31.456931+00:00 app[web.1]:     at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:77:44)
```

**Comment by mrmakeit** [comment] 2015-06-15 01:46
in the webhook settings, there is a "Recent Deliveries" section.  Can you open the most recent, and send me a copy of the payload section?

**Comment by groovecoder** [comment] 2015-06-16 12:32
I'm waiting for the comments to come in on https://github.com/groovecoder/sherwoodcourt.com/commit/28485239addcc05eed43411a97288f7f603c28b4. Payload delivered successfully:
![youshoulduse-sherwoodcourt-payload-delivery](https://cloud.githubusercontent.com/assets/71928/8182924/c6865ec4-13f9-11e5-9631-6cdf39fd28a6.png)
Logs show no error ...
```
2015-06-16T12:27:09.420508+00:00 heroku[router]: at=info method=POST path="/hook" host=youshoulduse.herokuapp.com request_id=e563df64-7eda-4965-b30d-286171302b3f fwd="192.30.252.40" dyno=web.1 connect=2ms service=5ms status=200 bytes=211
2015-06-16T12:27:09.419638+00:00 app[web.1]: Repo: groovecoder/sherwoodcourt.com
```

**Comment by darkwing** [comment] 2015-06-16 14:26
I've fixed my issue :)

**Comment by groovecoder** [comment] 2015-06-16 14:27
What was it?!

**Comment by mrmakeit** [comment] 2015-06-16 15:05
In your case @groovecoder, the only changes are ones thatare compatable.  Since the db update box-sizing is marked as working in all the browsers included by the default settings.

**Comment by groovecoder** [comment] 2015-06-17 18:13
Okay, I ran doiuse on a local file on the command line and got this:
```
lcrouch-14912:sherwoodcourt lcrouch$ doiuse styles.css
styles.css:20:1: CSS3 Transforms (2D) not supported by: IE (8), Opera Mini (5.0-8.0)
styles.css:28:1: CSS3 Transforms (2D) not supported by: IE (8), Opera Mini (5.0-8.0)
styles.css:169:1: CSS3 Transforms (2D) not supported by: IE (8), Opera Mini (5.0-8.0)
```
But https://github.com/groovecoder/sherwoodcourt.com/commit/da40b7edef99f2c330e38a8d97f574bd3b392c12 with a change to `text-transform` did **NOT** get a commit comment.
repo hook delivery shows success:
![youshoulduse-sherwood-hook-delivery](https://cloud.githubusercontent.com/assets/71928/8214958/7f90c618-14f2-11e5-9360-0b17fb0e3014.png)
`heroku logs` shows the hook payload delivered and recorded the repo:
```
2015-06-17T17:47:06.047738+00:00 heroku[router]: at=info method=POST path="/hook" host=youshoulduse.herokuapp.com request_id=6a497993-5ba0-449b-bbcd-70dcfebce8c4 fwd="192.30.252.42" dyno=web.1 connect=1ms service=3ms status=200 bytes=211
2015-06-17T17:47:06.043290+00:00 app[web.1]: Repo: groovecoder/sherwoodcourt.com
```

**Comment by groovecoder** [comment] 2015-06-17 18:20
Note: my repo has only a `gh-pages` branch.

**Comment by mrmakeit** [comment] 2015-06-18 00:35
I believe that ysh doesn't care what branch, but I'll double check when I
get home.  We may need to update the current version of doiuse.

On Wed, Jun 17, 2015, 13:20 luke crouch <notifications@github.com> wrote:

> Note: my repo has only a gh-pages branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdn/YouShouldUse/issues/46#issuecomment-112902640>.
>
-- 

-------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by mrmakeit** [comment] 2015-06-18 04:27
I'm going to force a reload on heroku to update doiuse.  In the mean time, I'm thinking of adding the payload to the logs for debugging.

**Comment by openjck** [comment] 2015-06-24 23:54
@groovecoder @darkwing: Are you still seeing this issue?

**Comment by groovecoder** [comment] 2015-06-29 19:46
Yup, I'm still getting this issue: https://github.com/groovecoder/sherwoodcourt.com/pull/4/files

Notes:
1. I've updated my webhook on my repo to the new mdn-discord settings
2. I'm pulling from an `uppercase` branch to a `gh-pages` branch in a repo with no `master` branch
3. I don't have a `.doiuse` file anywhere
4. I see output in the logs:
```
2015-06-29T19:43:55.580361+00:00 app[web.1]: Compatibility test requested from:
2015-06-29T19:43:55.580362+00:00 app[web.1]: groovecoder/sherwoodcourt.com
```
But no comments on the PR. :cry:

**Comment by openjck** [comment] 2015-06-29 20:05
Hm, it's possible it's not handling alternate branches. Does it work with master branches?

**Comment by mrmakeit** [comment] 2015-07-23 06:18
@groovecoder, can you verify this issue still exists?  Between all the changes this month, I'd like to verify this issue still occurs.

**Closed** 2015-07-23 14:09 UTC
Labels: backend, bug, GitHub, support
